# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('surnom', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('date_derniere_diffusion', models.DateTimeField(verbose_name='Date de la derniere emission')),
                ('contributeurs', models.ManyToManyField(to='radio.Animateur')),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_diffusion', models.DateTimeField()),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Emission')),
            ],
        ),
    ]
