# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20170303_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='dernier_episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='radio.Enregistrement'),
        ),
    ]
