# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_emission_dernier_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='emission_url',
            field=models.CharField(default='demo.mp3', max_length=200),
        ),
    ]
