# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_enregistrement_emission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='allow_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animateur',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='animateur',
            name='presentation',
            field=models.TextField(default=''),
        ),
    ]
