# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20170305_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('jour', models.CharField(choices=[('01LU', 'Lundi'), ('02MA', 'Mardi'), ('03ME', 'Mercredi'), ('04JE', 'Jeudi'), ('05VE', 'Vendredi'), ('06SA', 'Samedi'), ('07DI', 'Dimanche'), (None, 'Tous les jours')], default=None, max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='emission_url',
            field=models.CharField(default='demo.wav', max_length=200),
        ),
    ]
