# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_auto_20170312_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='jour',
            field=models.CharField(choices=[('00TS', 'Tous les jours'), ('01LU', 'Lundi'), ('02MA', 'Mardi'), ('03ME', 'Mercredi'), ('04JE', 'Jeudi'), ('05VE', 'Vendredi'), ('06SA', 'Samedi'), ('07DI', 'Dimanche'), (None, 'Choisis un jour')], default='00TS', max_length=4),
        ),
    ]
