# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20170312_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='playlist_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
